baseurl = "https://yamaneco.netlify.app"
title = "やまねこ学習帳"

theme = "hugo-coder"

languagecode = "ja"
defaultcontentlanguage = "ja"
hasCJKLanguage = true

paginate = 20
canonifyurls = true

#pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yamaneco05"

# googleAnalytics = ""

[Blackfriday]
hreftargetblank = true

[params]
    author = "yamaneco05"
    description = "yamaneco05's personal website"
    keywords = "blog, developer"
    info = "IT Engineer"
    avatarurl = "img/caticons.svg"

    favicon_32 = "img/favicony32.png"
    favicon_16 = "img/favicony32.png"

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true
    footercontent = "©yamaneco05."

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = ["css/style.css"]

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/yamaneco05/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/yamanecosan/"
#[[params.social]]
#    name = "Instagram"
#    icon = "fab fa-instagram"
#    weight = 4
#    url = "https://www.instagram.com/"


[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Contact me"
    weight = 5
    url = "/contact/"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "yamaneco study note"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "yamaneco05"
        info = "IT Engineer"
        description = "yamaneco's personal website"
        keywords = "blog, developer"

        [languages.en.menu] # It is possible to change the menu too.

        # [[languages.en.menu.main]]
        # name = "About"
        # weight = 1.0
        # url = "/en/about/"

        # [[languages.en.menu.main]]
        # name = "Blog"
        # weight = 2.0
        # url = "/en/posts/"

        # [[languages.en.menu.main]]
        # name = "Projects"
        # weight = 3
        # url = "/en/projects/"

        [[languages.en.menu.main]]
        name = "Bookshelf"
        weight = 4
        url = "/en/bookshelf/"
        
        # [[languages.en.menu.main]]
        # name = "Contact"
        # weight = 5
        # url = "/contact/"


    [languages.ja]
        languagename = "日本語"
        title = "やまねこ学習帳"

        [languages.ja.params]
            author = "yamaneco05"
            description = "yamaneco05のウェブサイト"
            keywords = "blog, developer"
            info = "エンジニア見習い"

        [languages.ja.menu]

            [[languages.ja.menu.main]]
            name = "プロフィール"
            weight = 1.0
            url = "/about/"

            [[languages.ja.menu.main]]
            name = "ブログ"
            weight = 2.0
            url = "/posts/"

            # [[languages.ja.menu.main]]
            # name = "プロジェクト"
            # weight = 3
            # url = "/projects/"
            
            [[languages.ja.menu.main]]
            name = "本棚"
            weight = 4
            url = "/bookshelf/"

            [[languages.ja.menu.main]]
            name = "Contact"
            weight = 5
            url = "/contact/"